version: "3"

services:
  db:
    image: postgres:15.2
    container_name: db-iop
    restart: always
    networks:
      - iop-django
    environment:
      - POSTGRES_DB=iop
      - POSTGRES_USER=iop
      - POSTGRES_PASSWORD=iop

  backend:
    container_name: backend-iop
    build:
      context: source/BE
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./source/BE:/BE
    environment:
      - DB_HOST=db
      - DB_NAME=iop
      - DB_USER=iop
      - DB_PASS=iop
    networks:
      - iop-django
    depends_on:
      - db

  nginx:
    image: nginx:1.23.3
    container_name: nginx-iop
    restart: always
    ports:
      - 8888:80
    depends_on: 
      - backend
    networks:
      - iop-django

volumes:
  db-data:

networks:
  iop-django: